import { ReceiptData, StoreProfile, PrintSettings, PlnTokenData } from '../types/receipt';

export const DEFAULT_PLN_TOKEN: PlnTokenData = {
  id: 'sample-pln-1',
  meterNumber: '32019482910',
  customerId: '52109823412',
  customerName: 'MUHAMMAD RIDWAN',
  tariffPower: 'R1 / 1300 VA',
  tokenNumber: '3819 4820 1928 4719 0192',
  kwhAmount: '65.8 kWh',
  amount: 100000,
  adminFee: 0,
  agentFee: 0,
  totalAmount: 100000,
  transactionDate: '16/09/2026',
  transactionTime: '19:30 WIB',
  refNumber: '20260916PLN101000297510',
  createdAt: new Date().toISOString(),
};

export const DEFAULT_STORE_PROFILE: StoreProfile = {
  storeName: 'MITRA FAMILY JUO',
  slogan: '',
  address: 'TANJUNG BELIT',
  postalCode: '28557',
  phone: '0812-9876-5432',
  callCenter: '08001014017 (BEBAS PULSA) TERIMAKASIH',
  footerMessage: 'INFORMASI LEBIH LANJUT, HUBUNGI',
  footerDisclaimer: 'SILAHKAN SIMPAN RESI INI SEBAGAI BUKTI PEMBAYARAN YANG SAH',
  defaultAgentFee: 0,
};

export const DEFAULT_PRINT_SETTINGS: PrintSettings = {
  paperWidth: '58mm',
  template: 'mini_atm',
  logoType: 'atm_bersama',
  receiptTitle: 'BUKTI TRANSAKSI MINI ATM',
  showBarcode: false,
  showQrCode: false,
  showAgentFee: false,
  showBankFee: false,
  showStatusBadge: false,
  showCustomerName: false,
  showNotes: false,
};

export const SAMPLE_RECEIPTS: ReceiptData[] = [
  {
    id: 'sample-mini-atm-bni',
    bankSource: 'MINI ATM',
    bankDestination: 'BNI',
    recipientName: 'GUNNER SILALAHI',
    recipientAccount: '1420117550',
    senderName: '',
    senderAccount: '',
    amount: 1800000,
    bankAdminFee: 0,
    agentFee: 0,
    totalAmount: 1800000,
    transactionDate: '16/09/2026',
    transactionTime: '19:30 WIB',
    refNumber: '20260916FAMAIDJ101000297510032',
    transactionType: 'TRANSFER ANTAR BANK',
    status: 'SUKSES',
    notes: '',
    customerName: '',
    cashierName: '',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'sample-bca-1',
    bankSource: 'BCA (m-BCA)',
    bankDestination: 'BRI',
    recipientName: 'ANDI PRASETYO',
    recipientAccount: '001901058291503',
    senderName: '',
    senderAccount: '',
    amount: 350000,
    bankAdminFee: 0,
    agentFee: 0,
    totalAmount: 350000,
    transactionDate: '05/10/2026',
    transactionTime: '10:45:12 WIB',
    refNumber: 'BCA2026100588291039',
    transactionType: 'TRANSFER BI-FAST',
    status: 'BERHASIL',
    notes: 'Pembayaran Belanja Toko',
    customerName: 'Pak Andi',
    cashierName: 'Kasir Dwi',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'sample-mandiri-2',
    bankSource: "Mandiri Livin'",
    bankDestination: 'BANK MANDIRI',
    recipientName: 'SITI NURHALIZA',
    recipientAccount: '1370019283741',
    senderName: '',
    senderAccount: '',
    amount: 1250000,
    bankAdminFee: 0,
    agentFee: 0,
    totalAmount: 1250000,
    transactionDate: '05/10/2026',
    transactionTime: '13:12:08 WIB',
    refNumber: 'MDR904812301984',
    transactionType: 'TRANSFER SESAMA MANDIRI',
    status: 'BERHASIL',
    notes: 'Kirim Uang Bulanan Anak',
    customerName: 'Ibu Siti',
    cashierName: 'Kasir Dwi',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'sample-brimo-3',
    bankSource: 'BRImo (Bank BRI)',
    bankDestination: 'BCA',
    recipientName: 'HENDRA WIJAYA',
    recipientAccount: '5220891234',
    senderName: '',
    senderAccount: '',
    amount: 750000,
    bankAdminFee: 0,
    agentFee: 0,
    totalAmount: 750000,
    transactionDate: '05/10/2026',
    transactionTime: '15:20:44 WIB',
    refNumber: 'BRILINK2026100599182',
    transactionType: 'TRANSFER ONLINE',
    status: 'BERHASIL',
    notes: 'DP Servis Motor',
    customerName: 'Mas Hendra',
    cashierName: 'Kasir Dwi',
    createdAt: new Date().toISOString(),
  },
];
